h=int(input("Enter the value of height: "))
b=int(input("Enter the  value of base:"))
t=lambda h,b:(.5*h*b)
print("Area of a triangle:",t(h,b))
a=int(input("Enter the square size of square:"))
s=lambda a:(a*a)
print("Area of square:",s(a))
l=int(input("Enter the lengh:"))
b1=int(input("Enter the breadth:"))
r=lambda l,b1:(l*b1)
print("Area of reactangle:",r(l,b1))
