h=int(input("Enter the value of height:"))
b=int(input("Enter the value of base:"))
t=lambda h,b:(.5*h*b)
print("Area of triangle:",t(h,b))
l=int(input("Enter the length:"))
br=int(input("Enter the breadth:"))
r=lambda l,br:(l*br)
print("Area of reactangle:",r(l,br))
a=int(input("Enter the square of the size:"))
s=lambda a:(a*a)
print("Area of square:",s(a))
